### ISSUE TITLE
Clarify statement of need and target audience

### ISSUE THREAD

**Issue by taqtiqa-mark** [gus0k/pymarket#10]
**Disclosure:** 
Carl Chiarella was a teacher then colleague of mine.

### Description
 It would be worth clarifying that the scope/target audience is **not** the financial economics domains or financial market microstucure domains.

These fields have developed deep and sophisticated specialties.
A flavor is given by:
 
@article{doi:10.1088/1469-7688/2/5/303,
author = { Carl   Chiarella  and  Giulia   Iori },
title = {A simulation analysis of the microstructure of double auction markets},
journal = {Quantitative Finance},
volume = {2},
number = {5},
pages = {346-353},
year  = {2002},
publisher = {Routledge},
doi = {10.1088/1469-7688/2/5/303},
URL = {https://www.tandfonline.com/doi/abs/10.1088/1469-7688/2/5/303},
eprint = {https://www.tandfonline.com/doi/pdf/10.1088/1469-7688/2/5/303},
abstract = { Abstract We introduce an order-driven market model with heterogeneous agents trading via a central order matching mechanism. Traders set bids and asks and post market or limit orders according to exogenously fixed rules. We investigate how different trading strategies may affect the dynamics of price, bid-ask spreads, trading volume and volatility. We also analyse how some features of market design, such as tick size and order lifetime, affect market liquidity. The model is able to reproduce many of the complex phenomena observed in real stock markets. *Paper presented at Applications of Physics in Financial Analysis (APFA) 3, 5–7 December 2001, Museum of London, UK. }} 

@article{doi:10.1088/1469-7688/1/2/307,
author = {   B.   LeBaron },
title = {A builder's guide to agent-based financial markets},
journal = {Quantitative Finance},
volume = {1},
number = {2},
pages = {254-261},
year  = {2001},
publisher = {Routledge},
doi = {10.1088/1469-7688/1/2/307},
URL = { https://doi.org/10.1088/1469-7688/1/2/307},
eprint = { https://doi.org/10.1088/1469-7688/1/2/307},    
abstract = { This paper is intended to guide researchers interested in building their own agent-based financial markets. Key design questions are outlined, along with some of the major controversies about which directions to take. }
}

**Comment by taqtiqa-mark** [comment]
You might also want to acknowledge Anton Kolotaev's work:
 
- described [here](https://www.slideshare.net/antonkolotaev/marketsim-components-code)
- with github code [here](https://github.com/fiquant/marketsimulator)

**Comment by gus0k** [comment]
Done

**Comment by taqtiqa-mark** [comment]
Can you point to the commits where this was done?  
In the commit message if you type "Closes issue #10" git hub will automatically cross link.
