### ISSUE TITLE
JOSS paper: Synchronize version numbers

### ISSUE THREAD

**Issue by taqtiqa-mark** [gus0k/pymarket#4]
Synchronize version numbers such that the JOSS release version given match the GitHub release.

**Comment by gus0k** [comment]
I more that willing to, but don't know how.

**Comment by gus0k** [comment]
Follow up: there is a whedon comment, but an editor has to do it.

**Comment by taqtiqa-mark** [comment]
Leave it to be the very last thing - in case there are further changes.
