### ISSUE TITLE
Incomplete install instructions

### ISSUE THREAD

**Issue by taqtiqa-mark** [gus0k/pymarket#5]
Is there not a clearly-stated list of system and python package dependencies
There are no instructions about how to handle these with an automated package management solution.

**Comment by gus0k** [comment]
I do not fully understanad what you mean by this. Dependencies are listed in requirements.txt and are automatically installed if the package is installed using pip. 
I can add to the read-the-docs if that is what you are asking.

**Comment by taqtiqa-mark** [comment]
Apologies for the ambiguity.
Yes please add instructions on installing requirements.
If there are no system requirements (ssl/ssh, graphics packages etc. etc.) implied by those python packages, then please add words to that effect.  

I've provided you with a vagrantfile with which to test your installation instructions starting from a clean system.

**Comment by gus0k** [comment]
I updated in the installation section a comment regarding the lack of external dependencies. I think that referring to the requeriments.txt should be enough regarding pure python dependencies.
