### ISSUE TITLE
Requirements specification incorrect: Matplotlib

### ISSUE THREAD

**Issue by taqtiqa-mark** [gus0k/pymarket#7]
### Description

To install pip packages the requirements file suggests there are no version restrictions.
A run of Travis CI clearly warns [at least one test will break for Matplotlib >=3.3](https://travis-ci.org/gus0k/pymarket/builds/578659316#L453)

**Comment by gus0k** [comment]
The dependency showing the error is not used, so that can be fixed easily.
I am not sure how I would go about to check the minimum version required for each library. Would you need me to do so?

**Comment by taqtiqa-mark** [comment]
Isn't there is a minimum python version?  this should be in the requirements file - I believe python allows this.

For package minimum versions take the smallest version numbers that you know to work the time of publication.  

**Yes please add minimum versions numbers** - the role of your users is not to discover minimum package versions by discovering/reporting what versions do not work.

**Comment by gus0k** [comment]
I added "minimum" versions in the requeriments.txt file as well as in the setup.py
