### ISSUE TITLE
Platforms (OS) tested and know to run on.

### ISSUE THREAD

**Issue by taqtiqa-mark** [gus0k/pymarket#8]
### Description

New users are in the dark about which platforms PyMarket is tested and known to run on: All?  
There are no platform specific gotchas in the package dependencies?

**Comment by gus0k** [comment]
I specified in the installation section that the library has been tested in Linux and Mac

**Comment by taqtiqa-mark** [comment]
> I specified in the installation section that the library has been tested in Linux and Mac

I don't believe you can claim this is true.  See issue #11.  A user would really have to want to use this library to persevere through this setup.  

Please update the install instructions to reflect:

1. What OS's pymarket has been tested to run on - So far it seems only Ubuntu Xenial 18.04? 
1. The install instructions and minimum versions for the OS's listed in 1.

**Comment by gus0k** [comment]
I don't understand why you don't believe in that claim.
There is a travis set up, running on linux and os: https://travis-ci.org/gus0k/pymarket/builds/597584718

As I explained while closing issue #11, that was a problem with the python version, not with the OS.

**Comment by taqtiqa-mark** [comment]
If you look at #11 you'll see it is a pip issue.
Your `.travis.yml` confirms that.

Nowhere do you state the latest pip has to be used, nor do you say how it should be upgraded.

Each distro has a 'supported' set of packages.  Each project has supported versions. Going outside of that generally means your on your own in terms of support contracts.

Please understand: very few users will preserver like this.

**Comment by gus0k** [comment]
I updated the installation instructions to reflect how to upgrade pip and python version

https://pymarket.readthedocs.io/en/master/installation.html

**Comment by taqtiqa-mark** [comment]
I'm sure your users will appreciate the clarity.

Please change:
> "PyMarket has been tested in Linux and mac OS."

to:

PyMarket has been tested in Ubutu Xenial (16.04) and mac OS.

In fact a find and replace /Linux/Ubuntu 16.04/, through out the code base is in order.

**Comment by gus0k** [comment]
Done, I updated the docs with specific versions. Manjaro is my local development environment

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
